from __future__ import annotations

import json
import logging
from typing import Any, Dict

from google import generativeai as genai

from .config import settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------
# Gemini setup
# ---------------------------------------------------------------------
if settings.GEMINI_API_KEY:
    try:
        genai.configure(api_key=settings.GEMINI_API_KEY)
        _model = genai.GenerativeModel(settings.GEMINI_MODEL_NAME)
        logger.info("Gemini model initialised: %s", settings.GEMINI_MODEL_NAME)
    except Exception as exc:
        logger.warning(
            "Failed to initialise Gemini model '%s': %s. Falling back to local content.",
            settings.GEMINI_MODEL_NAME,
            exc,
        )
        _model = None
else:
    logger.warning("GEMINI_API_KEY is not set. LLM calls will be skipped.")
    _model = None


# ---------------------------------------------------------------------
# Local fallback content
# ---------------------------------------------------------------------
def _fallback_content(topic: str) -> Dict[str, Any]:
    article = (
        f"{topic}\n\n"
        "This is a locally generated placeholder article because the live Gemini call "
        "failed (missing key, quota, or malformed response).\n\n"
        "In a real production environment, this content would be generated by the LLM."
    )

    seo = {
        "title": f"{topic} – AI Article",
        "description": f"Overview and key points about {topic}.",
        "keywords": [topic, "AI article", "SearchScribe AI Studio"],
        "og_title": f"{topic} – AI Article",
        "og_description": f"Auto-generated article about {topic}.",
    }

    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{seo["title"]}</title>
  <meta name="description" content="{seo["description"]}">
</head>
<body>
  <h1>{topic}</h1>
  <p>
    This is a locally generated placeholder article because the live Gemini call failed
    (missing key, quota, or malformed response).
  </p>
  <p>In a real production environment, this would come directly from the LLM.</p>
  <ul>
    <li>Topic: {topic}</li>
    <li>Generated by: Fallback content generator</li>
  </ul>
</body>
</html>
""".strip()

    return {
        "article": article,
        "seo": seo,
        "html": html,
        "model": "fallback",
        "is_fallback": True,
    }


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------
def _extract_text(response: Any) -> str:
    """
    Try to extract text from different possible response shapes
    (handles older and newer google-generativeai versions).
    """
    # Newer versions usually have .text
    if hasattr(response, "text") and response.text:
        return response.text

    # Older response structure: candidates -> content -> parts -> text
    try:
        candidates = getattr(response, "candidates", None) or []
        if not candidates:
            return str(response)

        parts = candidates[0].content.parts
        texts = []
        for p in parts:
            if hasattr(p, "text"):
                texts.append(p.text)
        if texts:
            return "".join(texts)
    except Exception:
        pass

    # Fallback: just string-ify
    return str(response)


def _parse_json_response(response: Any) -> Dict[str, Any]:
    raw = _extract_text(response)
    try:
        data = json.loads(raw)
        if not isinstance(data, dict):
            raise ValueError("Top-level JSON is not an object")
        return data
    except Exception as exc:
        logger.warning(
            "Gemini generation failed: Could not parse JSON from model response. "
            "Using local fallback content. Error: %s | Raw: %r",
            exc,
            raw[:200],
        )
        raise


# ---------------------------------------------------------------------
# Public functions used by routes
# ---------------------------------------------------------------------
def generate_article_with_html(topic: str) -> Dict[str, Any]:
    """
    Generate article + SEO + HTML.
    Never raises: on any Gemini error it returns local fallback.
    """
    if _model is None:
        return _fallback_content(topic)

    prompt = f"""
You are a JSON-only generator. Always respond ONLY in valid JSON.

Return a JSON object with exactly these fields:
- article: string (a well-structured article about "{topic}")
- seo: object with fields:
    - title: string
    - description: string
    - keywords: array of strings
    - og_title: string
    - og_description: string
- html: string (a complete minimal HTML <html> document rendering the article nicely)

STRICT RULES:
- Respond only with valid JSON.
- Do NOT wrap JSON in backticks.
- Do NOT include markdown.
- Do NOT include any explanation or prose outside the JSON.
"""

    try:
        # Use positional arg for the prompt to avoid funky unpack errors
        response = _model.generate_content(
            prompt,
            generation_config={"response_mime_type": "application/json"},
        )

        data = _parse_json_response(response)

        article = str(data.get("article", "")).strip()
        seo = data.get("seo") or {}
        html = str(data.get("html", "")).strip()

        if not article or not html:
            raise ValueError("Missing 'article' or 'html' in Gemini JSON payload")

        return {
            "article": article,
            "seo": seo,
            "html": html,
            "model": settings.GEMINI_MODEL_NAME,
            "is_fallback": False,
        }

    except Exception as exc:
        logger.warning("Gemini generate failed, returning fallback. Error: %s", exc)
        return _fallback_content(topic)


def regenerate_article_style(original_article: str, style: str) -> Dict[str, Any]:
    """
    Regenerate the article in a new style (e.g. 'Gen Z').
    Never raises: falls back to original article on any error.
    """
    if _model is None:
        regenerated = f"{original_article}\n\n[Note: reformatted in style: {style}]"
        return {
            "article": regenerated,
            "model": "fallback",
            "is_fallback": True,
        }

    prompt = f"""
You rewrite the given article into a new style.

Target style: {style}

Input article:
\"\"\"{original_article}\"\"\"

Return ONLY valid JSON with exactly one field:
- article: string (rewritten article in the requested style)

STRICT RULES:
- Respond only with valid JSON.
- Do NOT wrap JSON in backticks.
- Do NOT include markdown or any explanation outside the JSON.
"""

    try:
        response = _model.generate_content(
            prompt,
            generation_config={"response_mime_type": "application/json"},
        )

        data = _parse_json_response(response)
        article = str(data.get("article", "")).strip()

        if not article:
            raise ValueError("Missing 'article' in Gemini JSON payload")

        return {
            "article": article,
            "model": settings.GEMINI_MODEL_NAME,
            "is_fallback": False,
        }

    except Exception as exc:
        logger.warning(
            "Gemini regenerate failed, returning original article. Error: %s", exc
        )
        return {
            "article": original_article,
            "model": "fallback",
            "is_fallback": True,
        }
